version: "3"

services:
  database: 
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=poormansATS
    ports:
      - '5432:5432'
    volumes:
      - poormansATS-db:/var/lib/postgresql/data

volumes:
  poormansATS-db:
    driver: local
